from __future__ import annotations

import json
from pathlib import Path

from .analyzer import DatasetAnalysis


def write_json_report(analysis: DatasetAnalysis, path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(analysis.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")


def render_markdown_report(analysis: DatasetAnalysis) -> str:
    lines: list[str] = []

    lines.append(f"# CSV Analysis Report")
    lines.append("")
    lines.append(f"Source: `{analysis.source}`")
    lines.append("")
    lines.append(f"Rows: {analysis.row_count}")
    lines.append(f"Columns: {analysis.column_count}")
    lines.append("")

    lines.append("## Column profiles")
    lines.append("")
    lines.append("| Column | Type | Missing | Missing ratio | Unique | Key statistics |")
    lines.append("|---|---:|---:|---:|---:|---|")

    for column in analysis.columns:
        if column.numeric_summary:
            stats = column.numeric_summary
            stat_text = (
                f"min={stats['min']:.4g}, max={stats['max']:.4g}, "
                f"mean={stats['mean']:.4g}, median={stats['median']:.4g}"
            )
        else:
            top = ", ".join(f"{item['value']} ({item['count']})" for item in column.top_values[:3])
            stat_text = top or "n/a"

        lines.append(
            f"| {column.name} | {column.inferred_type} | {column.missing_count} | "
            f"{column.missing_ratio:.2%} | {column.unique_count} | {stat_text} |"
        )

    lines.append("")
    lines.append("## Correlations")
    lines.append("")

    if analysis.correlations:
        lines.append("| Column A | Column B | Pearson r | Pair count |")
        lines.append("|---|---|---:|---:|")
        for item in analysis.correlations[:20]:
            lines.append(
                f"| {item['column_a']} | {item['column_b']} | "
                f"{float(item['correlation']):.4f} | {item['pair_count']} |"
            )
    else:
        lines.append("No numeric correlations were computed.")

    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("This report was generated by the reconstructed CSV Analyzer Dashboard baseline.")
    lines.append("Type inference and statistics are educational and dependency-light.")

    return "\n".join(lines) + "\n"


def write_markdown_report(analysis: DatasetAnalysis, path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown_report(analysis), encoding="utf-8")


def compact_summary(analysis: DatasetAnalysis) -> str:
    numeric = sum(1 for column in analysis.columns if column.inferred_type in {"integer", "float"})
    categorical = sum(1 for column in analysis.columns if column.inferred_type == "categorical")
    missing_columns = sum(1 for column in analysis.columns if column.missing_count > 0)

    return (
        f"CSV Analysis Summary\n"
        f"Source: {analysis.source}\n"
        f"Rows: {analysis.row_count}\n"
        f"Columns: {analysis.column_count}\n"
        f"Numeric columns: {numeric}\n"
        f"Categorical columns: {categorical}\n"
        f"Columns with missing values: {missing_columns}\n"
        f"Correlations computed: {len(analysis.correlations)}"
    )
