from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from .intents import classify_intent, default_intents, response_for_intent
from .text_utils import is_exit_command


@dataclass
class Message:
    role: str
    text: str
    timestamp: str


@dataclass
class ChatBot:
    name: str = "ItalianVoiceBot"
    history: list[Message] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.intents = default_intents()

    def reply(self, user_text: str) -> str:
        timestamp = datetime.now().isoformat(timespec="seconds")
        self.history.append(Message(role="user", text=user_text, timestamp=timestamp))

        if user_text.strip() == "/help":
            response = (
                "Puoi scrivere: parlami di MicroBot, aiutami a studiare, ho bisogno di motivazione, "
                "privacy, oppure esci per chiudere. Usa /save per salvare il transcript."
            )
        elif is_exit_command(user_text):
            intent = classify_intent(user_text, self.intents)
            response = response_for_intent(intent)
        else:
            intent = classify_intent(user_text, self.intents)
            response = response_for_intent(intent)

        self.history.append(Message(role="assistant", text=response, timestamp=datetime.now().isoformat(timespec="seconds")))
        return response

    def should_exit(self, user_text: str) -> bool:
        return is_exit_command(user_text)

    def transcript_text(self) -> str:
        lines = [
            "Italian Voice Chatbot Transcript",
            "Generated by reconstructed skeleton",
            "",
        ]

        for message in self.history:
            lines.append(f"[{message.timestamp}] {message.role}: {message.text}")

        return "\n".join(lines).strip() + "\n"

    def save_transcript(self, directory: Path, suffix: str = "runtime") -> Path:
        directory.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = directory / f"chatbot_transcript_{timestamp}.{suffix}.txt"
        path.write_text(self.transcript_text(), encoding="utf-8")
        return path
