from __future__ import annotations

from pathlib import Path
from collections import Counter

from .composer import Composition
from .music_theory import midi_note_name


def composition_report(composition: Composition, midi_path: Path, wav_path: Path) -> str:
    track_counts = Counter(event.track for event in composition.events)

    lines = [
        f"# Composition report - {composition.title}",
        "",
        f"Title: {composition.title}",
        f"Style: {composition.style}",
        f"Key: {composition.key.root} {composition.key.scale}",
        f"Tempo: {composition.tempo} BPM",
        f"Bars: {composition.bars}",
        f"Duration beats: {composition.duration_beats:.2f}",
        f"Total events: {len(composition.events)}",
        f"MIDI output: {midi_path}",
        f"WAV preview: {wav_path}",
        "",
        "## Track event counts",
        "",
    ]

    for track, count in sorted(track_counts.items()):
        lines.append(f"{track}: {count}")

    melody_notes = [
        midi_note_name(event.note)
        for event in composition.events
        if event.track == "melody"
    ]

    lines.extend(
        [
            "",
            "## Melody preview",
            "",
            " ".join(melody_notes[:48]) if melody_notes else "No melody notes generated.",
            "",
            "## Responsible note",
            "",
            "This composition is generated by a simple educational algorithmic system. It is not a professional music production engine and does not claim authorship quality comparable to human composition.",
        ]
    )

    return "\n".join(lines).strip() + "\n"


def save_report(composition: Composition, midi_path: Path, wav_path: Path, report_path: Path) -> Path:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(composition_report(composition, midi_path, wav_path), encoding="utf-8")
    return report_path
